name: CI

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ development, main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and run tests
        run: |
          cd backend
          npm ci
          npm test

      - name: Build docker image
        run: |
          docker build -t ${GITHUB_REPOSITORY}:latest .
